package handler

import (
	"github.com/gin-gonic/gin"
	"github.com/lhducc/bookmark-management/internal/service"
	"net/http"
)

type healthCheckResponse struct {
	Message     string `json:"message"`
	ServiceName string `json:"serviceName"`
	InstanceID  string `json:"instanceID"`
}
type healthCheckHandler struct {
	svc service.HealthCheck
}

type HealthCheckHandler interface {
	Check(c *gin.Context)
}

func NewHealthCheckHandler(svc service.HealthCheck) HealthCheckHandler {
	return &healthCheckHandler{
		svc: svc,
	}
}

// Check handles a GET request to /health-check.
// It returns a JSON response with the following structure:
//
//	{
//	  "message": string,
//	  "serviceName": string,
//	  "instanceID": string
//	}
//
// The response is generated by calling the Check method of the service.HealthCheck interface.
// If the Check method of the service.HealthCheck interface returns an error, it returns an HTTP 500 error with the message 'err'.
// Otherwise, it returns an HTTP 200 OK response with the generated response as a JSON object.
func (h *healthCheckHandler) Check(c *gin.Context) {
	message, serviceName, instanceID := h.svc.Check()
	c.JSON(http.StatusOK, healthCheckResponse{
		Message:     message,
		ServiceName: serviceName,
		InstanceID:  instanceID,
	})
}
